#!/usr/bin/env node
// Codegen step: inlines the contents of skill-data/<name>/SKILL.md into a
// TypeScript module so the CLI can ship skills inside a Bun --compile binary,
// where fs paths to skill-data/ don't exist.
//
// Output: src/lib/skills-data.generated.ts (gitignored)

import { readdirSync, readFileSync, writeFileSync, statSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const srcDir = path.join(root, "skill-data");
const outFile = path.join(root, "src", "lib", "skills-data.generated.ts");

let names = [];
try {
  names = readdirSync(srcDir)
    .filter((n) => {
      try {
        return statSync(path.join(srcDir, n)).isDirectory();
      } catch {
        return false;
      }
    })
    .sort();
} catch (e) {
  console.error(`gen:skills: cannot read ${srcDir}: ${e.message}`);
  process.exit(1);
}

const entries = names.map((name) => {
  const file = path.join(srcDir, name, "SKILL.md");
  const content = readFileSync(file, "utf8");
  return { name, content };
});

let out = "// AUTO-GENERATED by scripts/gen-skills.mjs — do not edit.\n";
out += "// Run `npm run gen:skills` to regenerate.\n\n";
out += "export interface EmbeddedSkill {\n";
out += "  name: string;\n";
out += "  content: string;\n";
out += "}\n\n";
out += "export const EMBEDDED_SKILLS: Record<string, EmbeddedSkill> = {\n";
for (const { name, content } of entries) {
  out += `  ${JSON.stringify(name)}: {\n`;
  out += `    name: ${JSON.stringify(name)},\n`;
  out += `    content: ${JSON.stringify(content)},\n`;
  out += "  },\n";
}
out += "};\n";

mkdirSync(path.dirname(outFile), { recursive: true });
writeFileSync(outFile, out);
console.log(
  `gen:skills wrote ${entries.length} skill(s) to ${path.relative(root, outFile)}`,
);
